# Generated by Django 3.2 on 2023-03-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_auto_20230312_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='deprecated',
            field=models.BooleanField(default=False),
        ),
    ]
