# Generated by Django 3.2 on 2023-03-14 21:02

from django.db import migrations, models


def populate_values(apps, schema_editor):
    ProspectModel = apps.get_model('prospects', 'Prospect')

    for prospect in ProspectModel.objects.all():
        prospect.full_name = "{} {}".format(prospect.first_name, prospect.last_name)
        prospect.save()


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(populate_values)
    ]
