# Generated by Django 3.2 on 2023-03-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0002_prospect_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
