# Generated by Django 3.2 on 2023-04-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0005_auto_20230314_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
