# Generated by Django 3.2 on 2023-05-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0006_alter_prospect_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=150, unique=True),
        ),
    ]
