# Generated by Django 3.2 on 2023-03-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='msg_tracking_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='msg_tracking_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
