# Generated by Django 3.2 on 2023-04-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230329_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='openai_model',
            field=models.CharField(default='gpt-3.5-turbo', max_length=255),
        ),
    ]
