# Generated by Django 3.2 on 2023-04-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230419_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auto_save',
            field=models.BooleanField(default=False),
        ),
    ]
