# Generated by Django 3.2 on 2023-03-12 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prompts', '0002_auto_20230312_0954'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('raw', models.JSONField()),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prompts.prompt')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospects.prospect')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('raw', models.JSONField()),
                ('parsed', models.TextField()),
                ('copied', models.BooleanField(default=False)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='openai_messages.messageset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
