# Generated by Django 3.2 on 2023-03-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openai_messages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='raw',
        ),
    ]
