# Generated by Django 3.2 on 2023-03-19 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0003_prompt_deprecated'),
        ('templates', '0003_auto_20230319_1056'),
        ('openai_messages', '0002_remove_message_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageset',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='templates.template'),
        ),
        migrations.AlterField(
            model_name='messageset',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prompts.prompt'),
        ),
    ]
