# Generated by Django 3.2 on 2023-03-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai_messages', '0003_auto_20230319_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageset',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messageset',
            name='raw',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
