# Generated by Django 3.2 on 2023-03-24 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openai_messages', '0005_messageset_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageset',
            name='prompt',
        ),
    ]
