# Generated by Django 3.2 on 2023-03-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai_messages', '0007_linkedinmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinmessage',
            name='profile_slug',
            field=models.SlugField(),
        ),
    ]
