# Generated by Django 3.2 on 2023-03-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai_messages', '0008_alter_linkedinmessage_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinmessage',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkedinmessage',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
