# Generated by Django 3.2 on 2023-04-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai_messages', '0010_linkedincomment_linkedinlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedincomment',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkedincomment',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='linkedinlike',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkedinlike',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
