# Generated by Django 3.2 on 2023-03-26 19:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('signature', models.TextField()),
                ('scope', models.TextField()),
                ('id_token', models.TextField()),
                ('instance_url', models.TextField()),
                ('token_type', models.TextField()),
                ('issued_at', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
