# Generated by Django 3.2 on 2023-03-26 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('salesforce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='company',
            field=models.ForeignKey(default='554fd847-4564-4ba1-bca8-d9d1f15b81f1', on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
            preserve_default=False,
        ),
    ]
