# Generated by Django 3.2 on 2023-03-29 20:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('openai_messages', '0009_auto_20230329_2008'),
        ('salesforce', '0002_credentials_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('task_id', models.CharField(max_length=255)),
                ('msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openai_messages.linkedinmessage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
