# Generated by Django 3.2 on 2023-03-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='linkedin_field_is_custom',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='credentials',
            name='linkedin_field_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
