# Generated by Django 3.2 on 2023-04-24 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openai_messages', '0011_auto_20230424_1435'),
        ('salesforce', '0005_remove_credentials_linkedin_field_is_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='openai_messages.linkedincomment'),
        ),
        migrations.AddField(
            model_name='task',
            name='like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='openai_messages.linkedinlike'),
        ),
        migrations.AlterField(
            model_name='task',
            name='msg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='openai_messages.linkedinmessage'),
        ),
    ]
