# Generated by Django 3.2 on 2023-03-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_template_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='meta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='templatesection',
            name='meta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
