# Generated by Django 3.2 on 2023-03-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_template_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='company',
        ),
        migrations.AddField(
            model_name='template',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
